# Site settings
title: On The Wind
email: orga.shih@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Orga talks anything about nothing A_AY.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sinorga.github.io" # the base hostname & protocol for your site
github_username:  sinorga

# Build settings
markdown: kramdown
